sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.7
cache: pip
install: pip install coverage
addons:
  apt:
    packages:
    - doxygen
script:
  - nosetests --exe --with-coverage --cover-branches test
after_success:
  - bash <(curl -s https://codecov.io/bash)
