language: python
dist: focal
python:
  - 2.7
  - 3.7
  - 3.8
  - 3.9
cache: pip
install: pip install coverage
script:
  - nosetests --exe --with-coverage --cover-branches test
after_success:
  - bash <(curl -s https://codecov.io/bash)
